name: robomongo
version: 1.0.0
summary: Robomongo
description: Native and cross-platform MongoDB manager
confinement: strict

apps:
    robomongo:
        command: env LC_ALL=C QT_XKB_CONFIG_ROOT="$SNAP/usr/share/X11/xkb" desktop-launch robomongo
        plugs: [home, network, unity7]

parts:
    tarball:
        plugin: dump
        source: https://download.robomongo.org/1.0.0/linux/robomongo-1.0.0-linux-x86_64-89f24ea.tar.gz
        after: [desktop/qt5]
